library(plyr)
# given after plot1 exercise, the raw data file has been downloaded and unzipped into working directory
data<-read.table("household_power_consumption.txt", header=TRUE, sep=";", na.strings="?", nrow=100000)
subdata<-droplevels(subset(data, Date %in% c("1/2/2007","2/2/2007")))
subdata<-mutate(subdata, DateTime=strptime(paste(Date, Time, sep=" "), "%d/%m/%Y %H:%M:%S"))
subdata<-subdata[, -c(1:2)]
png(filename="plot4.png", width=480, height=480, units="px")
par(mfcol=c(2,2))
plot(subdata$DateTime, subdata$Global_active_power, xlab="", ylab="Global Active Power", type="l")
plot(subdata$DateTime, subdata$Sub_metering_1, xlab="", ylab="Energy sub metering", type="l", col="black")
lines(subdata$DateTime, subdata$Sub_metering_2, col="red")
lines(subdata$DateTime, subdata$Sub_metering_3, col="blue")
legend("topright", lty=1, col=c("black", "blue", "red"), bty="n", legend=c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(subdata$DateTime, subdata$Voltage, xlab="datetime", ylab="Voltage", type="l", col="black")
plot(subdata$DateTime, subdata$Global_reactive_power, xlab="datetime", ylab="Global_reactive_power", type="l", col="black")
dev.off()
